const APP_ID = 'com.renapsi.buscaabrangencia';
const ACTIVE_OPACITY = 1;
const IDLE_OPACITY = 0.68;
const IDLE_DELAY_MS = 8000;
const BASE_WIDTH = 760;
const INITIAL_CONTENT_HEIGHT = 62;
const MIN_CONTENT_HEIGHT = 62;
const MAX_CONTENT_HEIGHT = 520;
const MIN_SCALE = 0.62;
const MAX_SCALE = 1.8;
const SAFETY_WIDTH = 16;
const MIN_WINDOW_WIDTH = Math.ceil(BASE_WIDTH * MIN_SCALE) + SAFETY_WIDTH;
const MAX_WINDOW_WIDTH = Math.ceil(BASE_WIDTH * MAX_SCALE);

module.exports = {
  APP_ID,
  ACTIVE_OPACITY,
  IDLE_OPACITY,
  IDLE_DELAY_MS,
  BASE_WIDTH,
  INITIAL_CONTENT_HEIGHT,
  MIN_CONTENT_HEIGHT,
  MAX_CONTENT_HEIGHT,
  MIN_SCALE,
  MAX_SCALE,
  MIN_WINDOW_WIDTH,
  MAX_WINDOW_WIDTH
};
